name: Deploy application

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "202[3-9].[0-9][0-9].[0-9]+-rc[0-9]+"
      - "202[3-9].[0-9][0-9].[0-9]+"

concurrency:
  group: ${{ github.ref_type != 'tag' && 'dev' || contains(github.ref, '-rc') && 'test' || 'prod' }}
  cancel-in-progress: false # Set to true to cancel old runs for new ones

permissions:
  id-token: write
  contents: read
  packages: write     
  attestations: write

jobs:
  publish-image:
    uses: ./.github/workflows/publish_image.yml
  
  create-infra:
    needs: publish-image
    runs-on: ubuntu-latest
    # Selects 'dev' for push to main, 'test' for -rc tags, 'prod' for regular tags
    environment: >-
      ${{ github.ref_name == 'main' && 'dev' ||
          (contains(github.ref, '-rc') && 'test' || 'prod') }}
    
    defaults:
      run:
        working-directory: infra/terraform

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Terraform init
      run: |
        terraform init \
          -backend-config="key=${{ vars.TFSTATE_PREFIX }}.terraform.tfstate"
    
    - name: Select Terraform Workspace
      run: |
        terraform workspace select vars.TFWORKSPACE || terraform workspace new vars.TFWORKSPACE

    - name: Terraform Apply
      run: |
        terraform apply \
          -var "container_tag=${{ github.sha }}" \
          -var "subscription_id=${{ secrets.AZURE_MI_SUBSCRIPTION_ID }}" \
          -auto-approve
    
