name: Deploy Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "202[3-9].[0-9][0-9].[0-9]+-rc[0-9]+"
      - "202[3-9].[0-9][0-9].[0-9]+"

concurrency:
  group: ${{ github.ref_type != 'tag' && github.ref_name || contains(github.ref, '-rc') && 'test' || 'prod' }}
  cancel-in-progress: false # Set to true to cancel old runs for new ones

permissions:
  id-token: write
  contents: read

jobs:
  create-infra:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: infra/terraform

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Gather Diagnostics for MS Support
      run: |
        echo "=== Output of az version ==="
        az version
        
        echo "=== Output of az extension show ==="
        # Explicitly add the extension so we can query its version details
        az config set extension.use_dynamic_install=yes_without_prompt
        az extension add --name azure-devops
        az extension show --name azure-devops
    
    - name: Trigger Azure Pipeline
      id: trigger_pipeline
      run: |
        echo "Getting ADO OAuth token"

        TOKEN_RESPONSE=$(curl -sS -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.AZURE_ADO_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.AZURE_ADO_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials" \
            -d "scope=499b84ac-1321-427f-aa17-267ca6975798/.default" \
            "https://login.microsoftonline.com/${{ secrets.AZURE_ADO_TENANT_ID }}/oauth2/v2.0/token")

          export AZURE_DEVOPS_EXT_PAT=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token // empty')

          if [ -z "$AZURE_DEVOPS_EXT_PAT" ]; then
            echo "Failed to get Azure DevOps token"
            exit 1
          fi

        echo "Received ADO OAuth token"
        RUN_ID=$(az pipelines run \
          --id "1" \
          --org "${{ secrets.AZURE_ADO_ORG_URL }}" \
          --project "${{ secrets.AZURE_ADO_PROJECT }}" \
          --branch "${{ github.ref }}" \
          --commit-id ${{ github.sha }} \
          --query "id" -o tsv)

        echo "Waiting for Azure DevOps Pipeline run to complete..."
        while true; do
          PIPELINE_STATUS=$(az pipelines runs show \
            --id $RUN_ID \
            --org "${{ secrets.AZURE_ADO_ORG_URL }}" \
            --project "${{ secrets.AZURE_ADO_PROJECT }}" \
            --query "status" -o tsv)

          echo "Current pipeline status: $PIPELINE_STATUS"

          if [[ "$PIPELINE_STATUS" == "completed" ]]; then
            PIPELINE_RESULT=$(az pipelines runs show \
              --id $RUN_ID \
              --org "${{ secrets.AZURE_ADO_ORG_URL }}" \
              --project "${{ secrets.AZURE_ADO_PROJECT }}" \
              --query "result" -o tsv)

            echo "Pipeline completed with result: $PIPELINE_RESULT"
            if [[ "$PIPELINE_RESULT" == "succeeded" ]]; then
              exit 0
            else
              echo "Azure DevOps Pipeline failed with result: $PIPELINE_RESULT"
              exit 1
            fi
          elif [[ "$PIPELINE_STATUS" == "cancelling" || "$PIPELINE_STATUS" == "notStarted" || "$PIPELINE_STATUS" == "inProgress" ]]; then
            sleep 10
          else
            echo "Azure DevOps Pipeline finished with unexpected status: $PIPELINE_STATUS"
            exit 1
          fi
        done
